import {
  LayoutDashboard,
  ChefHat,
  Truck,
  ClipboardList,
  Plus,
  Tag,
  Package,
  Users,
  Menu,
  X,
  LogOut,
  Search,
  Camera,
  Check,
  Star,
  Bell,
  Pencil,
  Ticket,
  type LucideProps,
} from "lucide-react";

export const Icon = {
  dashboard: (p: LucideProps) => <LayoutDashboard size={20} strokeWidth={2} {...p} />,
  kitchen: (p: LucideProps) => <ChefHat size={20} strokeWidth={2} {...p} />,
  dispatch: (p: LucideProps) => <Truck size={20} strokeWidth={2} {...p} />,
  orders: (p: LucideProps) => <ClipboardList size={20} strokeWidth={2} {...p} />,
  plus: (p: LucideProps) => <Plus size={20} strokeWidth={2} {...p} />,
  tag: (p: LucideProps) => <Tag size={20} strokeWidth={2} {...p} />,
  box: (p: LucideProps) => <Package size={20} strokeWidth={2} {...p} />,
  users: (p: LucideProps) => <Users size={20} strokeWidth={2} {...p} />,
  truck: (p: LucideProps) => <Truck size={20} strokeWidth={2} {...p} />,
  menu: (p: LucideProps) => <Menu size={20} strokeWidth={2} {...p} />,
  x: (p: LucideProps) => <X size={20} strokeWidth={2} {...p} />,
  logout: (p: LucideProps) => <LogOut size={20} strokeWidth={2} {...p} />,
  search: (p: LucideProps) => <Search size={20} strokeWidth={2} {...p} />,
  camera: (p: LucideProps) => <Camera size={20} strokeWidth={2} {...p} />,
  check: (p: LucideProps) => <Check size={20} strokeWidth={2} {...p} />,
  star: (p: LucideProps) => <Star size={20} strokeWidth={2} {...p} />,
  bell: (p: LucideProps) => <Bell size={20} strokeWidth={2} {...p} />,
  edit: (p: LucideProps) => <Pencil size={20} strokeWidth={2} {...p} />,
  ticket: (p: LucideProps) => <Ticket size={20} strokeWidth={2} {...p} />,
};
